// <auto-generated />
using DynamicAppBuilder.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicAppBuilder.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250301201820_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("DynamicAppBuilder.Server.Models.ControlProperties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Options")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Placeholder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PropId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("defaultValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropId");

                    b.ToTable("ControlProperties");
                });

            modelBuilder.Entity("DynamicAppBuilder.Server.Models.Props", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Props");
                });

            modelBuilder.Entity("DynamicAppBuilder.Server.Models.ControlProperties", b =>
                {
                    b.HasOne("DynamicAppBuilder.Server.Models.Props", "Prop")
                        .WithMany("ControlProperties")
                        .HasForeignKey("PropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DynamicAppBuilder.Server.Models.Coordinates", "coordinates", b1 =>
                        {
                            b1.Property<int>("ControlPropertiesId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("X")
                                .HasColumnType("REAL");

                            b1.Property<double>("Y")
                                .HasColumnType("REAL");

                            b1.HasKey("ControlPropertiesId");

                            b1.ToTable("ControlProperties");

                            b1.WithOwner()
                                .HasForeignKey("ControlPropertiesId");
                        });

                    b.Navigation("Prop");

                    b.Navigation("coordinates")
                        .IsRequired();
                });

            modelBuilder.Entity("DynamicAppBuilder.Server.Models.Props", b =>
                {
                    b.Navigation("ControlProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
